module.exports = {
  HIGH_EXPENSE_THRESHOLD: parseInt(process.env.INSIGHT_HIGH_EXPENSE_THRESHOLD, 10) || 5000,
  CRITICAL_STOCK_UNITS: parseInt(process.env.INSIGHT_CRITICAL_STOCK_UNITS, 10) || 5,
  SALES_DROP_THRESHOLD: parseFloat(process.env.INSIGHT_SALES_DROP_THRESHOLD) || 0.5,
  REVENUE_DECLINE_THRESHOLD: parseFloat(process.env.INSIGHT_REVENUE_DECLINE_THRESHOLD) || 0.01,
  STOCK_DEPLETION_DAYS: parseInt(process.env.INSIGHT_STOCK_DEPLETION_DAYS, 10) || 7,
  SALES_VELOCITY_LOOKBACK_DAYS: parseInt(process.env.INSIGHT_VELOCITY_LOOKBACK_DAYS, 10) || 14,
  AI_SERVICE_TIMEOUT_MS: parseInt(process.env.AI_SERVICE_TIMEOUT_MS, 10) || 15000,
};
