import { isNativeAndroid } from '../utils/capacitorEnv';

/**
 * Service worker registration and update state.
 *
 * The service worker (generated by vite-plugin-pwa) stores the app itself on the device so it opens without a
 * connection. New versions are NOT applied automatically: a cashier in the middle of a sale must not have
 * the page reload under them. Instead `needRefresh` becomes true and the update prompt lets them choose.
 */

const UPDATE_CHECK_INTERVAL_MS = 60 * 60 * 1000; // look for a new version every hour (tills stay open all day)

let state = { needRefresh: false, offlineReady: false };
let updateSW = null;
const listeners = new Set();

const emit = (patch) => {
  state = { ...state, ...patch };
  listeners.forEach((listener) => listener());
};

export const getPwaState = () => state;

export function subscribePwa(listener) {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

export function dismissPwaPrompt() {
  emit({ needRefresh: false, offlineReady: false });
}

/** Activate the waiting version and reload the page. */
export async function applyPwaUpdate() {
  if (updateSW) await updateSW(true);
}

/**
 * @param {object} [options]
 * @param {() => Promise<{registerSW: Function}>} [options.importRegister]  injectable for tests
 * @returns {Promise<Function|null>}
 */
export async function registerServiceWorker({ importRegister = () => import('virtual:pwa-register') } = {}) {
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return null;
  // The Android app ships its own copy of the web app, so a service worker would only get in the way.
  if (isNativeAndroid()) return null;

  try {
    const { registerSW } = await importRegister();
    updateSW = registerSW({
      onNeedRefresh: () => emit({ needRefresh: true }),
      onOfflineReady: () => emit({ offlineReady: true }),
      onRegisteredSW(_url, registration) {
        if (registration) {
          setInterval(() => {
            registration.update().catch(() => {});
          }, UPDATE_CHECK_INTERVAL_MS);
        }
      },
      onRegisterError(error) {
        console.warn('Service worker registration failed:', error);
      },
    });
    return updateSW;
  } catch (error) {
    console.warn('Service worker could not be set up:', error);
    return null;
  }
}
